### ISSUE TITLE
Small problem with inputting files

### ISSUE THREAD

**Issue by SoaringGecko** [rondotcomYT/Infinity-Drive#2] opened 2023-03-16 18:20 UTC
When inputting a file using `""` will cause the file to not be detected.

```
What file should I decode? (i.e Infinity-Drive.mp4): "D:\Infinity-Drive\Infinity-Drive.mp4"
Oops! File does not exist.
```

```
What file should I decode?: D:\Infinity-Drive\Infinity-Drive.mp4
What should I name the output file? (i.e output.zip):
```

The progress bar is also missing while encoding (if there is supposed to be one)

**Comment by rondotcomYT** [comment] 2023-03-16 19:41
Thank you for alerting me to this! Should be fixed now :)
As far as the progress bar goes, there isn't one _yet_, but I do plan on implementing it soon.

**Comment by pixelomer** [comment] 2023-03-16 20:57
This was not a bug. There is no reason for the program to handle quotes when it is expecting a file path. Furthermore, the fix for this issue creates a new, bigger issue: File paths with quotes in them can no longer be used.

**Closed as not planned** 2023-03-16 21:34 UTC
Labels: wontfix

**Comment by rondotcomYT** [comment] 2023-03-16 21:35
Thank you @pixelomer

**Comment by SoaringGecko** [comment] 2023-03-18 02:34
only reason why I bring it up is if someone where to have a file path with a space in it like `new folder` it wouldn't work

**Comment by rondotcomYT** [comment] 2023-03-18 04:57
That's odd, as far as I can tell from my testing I've had no issues with spaces in folder or file names.

What OS are you using? I run most of my code on a Mac, but I have a Windows machine as well and they have both not given me any trouble.

**Comment by SoaringGecko** [comment] 2023-03-18 17:48
I apologize this may have actually been a user error on my part as I just tried to do it again and it worked. (also win10 if you still want it)
